### ISSUE TITLE
کمک میخواستم

### ISSUE THREAD

**Issue by Alirezanassari** [HrBDev/myket-apk-downloader#246]
سلام 👋
داداش🙏🌹🔥❤ نمیدونم آنلاین هستی یا نه میخواستم بدونم چطوری بتونم 
authBody 
گوشی یا دیوایس اندرویدی خودم را بدست بیارم برای مایکت
و آیا کدی چیزی هست یا باید دیتای prefs مایکت رو خوند
البته بیشتر نیاز به استخراج دو پارامتر hsh و uuid هستم 
امیدوارم بتونی کمکم کنی❤

**Comment by HrBDev** [comment]
برای گرفتن authBody از ترکیب Pcap remote و Wireshark استفاده کردم این داده های رد و بدل شده بین برنامه android مایکت و سرور هست چیزی از داخل برنامه نخوندم

**Comment by Alirezanassari** [comment]
> برای گرفتن authBody از ترکیب Pcap remote و Wireshark استفاده کردم این داده های رد و بدل شده بین برنامه android مایکت و سرور هست چیزی از داخل برنامه نخوندم 

سلام داداش وقت بخیر 👋
از راهنمایی خیلی خیلی ممنون 
واقعا لطف بزرگی کردی

من داشتم تلاش بیهوده میکردم
اومدم با BurpSuite این کارو انجام بدم 
ولی تلاش میکردم و تنها چیزی روی اون کار میکرد فقط مرورگر هست

حقیقتش راهنماییت خیلی کمکم کرد❤️‍🔥🫂😊

**Comment by Alirezanassari** [comment]
سلام داداش👋🫂❤️‍🔥 
ببخشید مزاحم میشم 
یه نرم‌افزار داخل **Google Play** پلی کردم🙂
که همون کارو میکنه
و اسم نرم‌افزار **Reqable** هست
لینک :
**[Reqable Download Link Google Play](https://play.google.com/store/apps/details?id=com.reqable.android)
**

که وقتی نصب میکنی قبل از استارت باید از بخش 
**Certificate Management**
بخش  
**Install Root Certificate to Local-Machine**

همچی رو توضیح داده هم برای دستگاه‌های روت شده و هم روت نشده❤️‍🔥
